Made turret point directly towards mouse
Wolfyxon/TurretSiege pull request #3
Opened 2024-10-05 01:54 UTC by jiffygist

I just adjust mouse coords by world aspect ratio so they are not stretched (like if you would set `data.width` equal to `data.height`). Idk how you would want to expose `data.width` and `data.height` to your Turret class, so I just made `data` global.

Fixes #1

2024-10-05 11:25 UTC, Wolfyxon commented
Well the issue doesn't exactly lie within the turret but all nodes

2024-10-05 11:31 UTC, Wolfyxon requested changes

2024-10-05 11:31 UTC, Wolfyxon commented on src/main.lua
> -local data = require("data")
`data` should not be global but imported where needed.

2024-10-05 11:31 UTC, Wolfyxon commented on src/scenes/game/turret/turret.lua
> +            x = x*(data.width/data.height)
Please use spaces in calculations to make them more readable, for example
```
a + b * c
```

2024-10-05 16:31 UTC, jiffygist commented
did the changes

2024-10-10 12:12 UTC, Wolfyxon commented
Merging as a temporary fix

2024-10-10 12:13 UTC, merged